export const ZAKAT_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_usdcTokenAddress", type: "address" },
      { internalType: "address", name: "_treasuryAddress", type: "address" },
      { internalType: "address", name: "_timelockAddress", type: "address" },
      { internalType: "address", name: "_zakatNFTAddress", type: "address" },
      { internalType: "address", name: "_tempAdminAddress", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AccessControlBadConfirmation", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "bytes32", name: "neededRole", type: "bytes32" },
    ],
    name: "AccessControlUnauthorizedAccount",
    type: "error",
  },
  {
    inputs: [{ internalType: "string", name: "entity", type: "string" }],
    name: "AddressZero",
    type: "error",
  },
  {
    inputs: [{ internalType: "string", name: "entity", type: "string" }],
    name: "AlreadyAllocated",
    type: "error",
  },
  {
    inputs: [{ internalType: "string", name: "entity", type: "string" }],
    name: "AlreadyDistributed",
    type: "error",
  },
  {
    inputs: [{ internalType: "string", name: "entity", type: "string" }],
    name: "AlreadyRegistered",
    type: "error",
  },
  {
    inputs: [{ internalType: "string", name: "entity", type: "string" }],
    name: "AlreadyUnverified",
    type: "error",
  },
  {
    inputs: [{ internalType: "string", name: "entity", type: "string" }],
    name: "AlreadyVerified",
    type: "error",
  },
  {
    inputs: [{ internalType: "string", name: "field", type: "string" }],
    name: "EmptyString",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint256", name: "available", type: "uint256" },
      { internalType: "uint256", name: "requested", type: "uint256" },
    ],
    name: "InsufficientBalance",
    type: "error",
  },
  {
    inputs: [{ internalType: "string", name: "field", type: "string" }],
    name: "InvalidAmount",
    type: "error",
  },
  {
    inputs: [{ internalType: "string", name: "entity", type: "string" }],
    name: "NotAvailable",
    type: "error",
  },
  {
    inputs: [{ internalType: "string", name: "entity", type: "string" }],
    name: "NotFound",
    type: "error",
  },
  {
    inputs: [{ internalType: "string", name: "entity", type: "string" }],
    name: "NotRegistered",
    type: "error",
  },
  {
    inputs: [{ internalType: "string", name: "entity", type: "string" }],
    name: "NotVerified",
    type: "error",
  },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "distributionId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "approvedAmount",
        type: "uint256",
      },
    ],
    name: "DistributionApproved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "distributionId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "beneficiaryCount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reportUri",
        type: "string",
      },
    ],
    name: "DistributionCompleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "distributionId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "organizationAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "requestedAmount",
        type: "uint256",
      },
    ],
    name: "DistributionProposed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "bytes32",
        name: "previousAdminRole",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "newAdminRole",
        type: "bytes32",
      },
    ],
    name: "RoleAdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "distributionId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "organizationAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "ZakatDistributed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "donor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "donationId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "netAmount",
        type: "uint256",
      },
    ],
    name: "ZakatDonated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "distributionId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalCertificates",
        type: "uint256",
      },
    ],
    name: "ZakatNFTCertificatesMinted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "organizationAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "organizationId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "organizationName",
        type: "string",
      },
    ],
    name: "ZakatOrganizationEdited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "organizationAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "organizationId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "organizationName",
        type: "string",
      },
    ],
    name: "ZakatOrganizationRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "organizationAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "organizationId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isVerified",
        type: "bool",
      },
    ],
    name: "ZakatOrganizationVerifyUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldTipBps",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newTipBps",
        type: "uint256",
      },
    ],
    name: "ZakatPlatformFeeUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "BPS_BASE",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "GOVERNER_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_distributionId", type: "uint256" },
      { internalType: "uint256[]", name: "_donationIds", type: "uint256[]" },
    ],
    name: "allocateDonationsToDistribution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_distributionId", type: "uint256" },
      { internalType: "uint256", name: "_approvedAmount", type: "uint256" },
    ],
    name: "approveDistribution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_donationAmount", type: "uint256" },
      { internalType: "uint256", name: "_tipAmount", type: "uint256" },
    ],
    name: "calculateDonationAmounts",
    outputs: [
      { internalType: "uint256", name: "totalAmount", type: "uint256" },
      { internalType: "uint256", name: "netAmount", type: "uint256" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_distributionId", type: "uint256" },
      {
        internalType: "uint256",
        name: "_actualBeneficiaryCount",
        type: "uint256",
      },
      { internalType: "string", name: "_reportUri", type: "string" },
      { internalType: "string", name: "_certificateURI", type: "string" },
    ],
    name: "completeDistributionAndMintCertificates",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_distributionId", type: "uint256" },
    ],
    name: "distributeZakat",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "uint256", name: "_tipAmount", type: "uint256" },
      {
        internalType: "enum Zakat.ZakatType",
        name: "_zakatType",
        type: "uint8",
      },
      { internalType: "string", name: "_donorMessage", type: "string" },
    ],
    name: "donateZakat",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_organizationAddress",
        type: "address",
      },
      { internalType: "string", name: "_name", type: "string" },
      { internalType: "string", name: "_contactInfo", type: "string" },
      { internalType: "string", name: "_location", type: "string" },
      { internalType: "string", name: "_description", type: "string" },
      { internalType: "string", name: "_registrationNumber", type: "string" },
    ],
    name: "editZakatOrganization",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_distributionId", type: "uint256" },
    ],
    name: "getDistributionDonations",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_distributionId", type: "uint256" },
    ],
    name: "getDistributionInfo",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "uint256", name: "organizationId", type: "uint256" },
          {
            internalType: "address",
            name: "organizationAddress",
            type: "address",
          },
          { internalType: "uint256", name: "requestedAmount", type: "uint256" },
          { internalType: "uint256", name: "approvedAmount", type: "uint256" },
          {
            internalType: "uint256",
            name: "distributedAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "beneficiaryCount",
            type: "uint256",
          },
          {
            internalType: "enum Zakat.DistributionType",
            name: "distributionType",
            type: "uint8",
          },
          {
            internalType: "enum Zakat.DistributionStatus",
            name: "status",
            type: "uint8",
          },
          { internalType: "string", name: "title", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          { internalType: "string", name: "location", type: "string" },
          { internalType: "string", name: "reportUri", type: "string" },
          { internalType: "uint256", name: "createdAt", type: "uint256" },
          { internalType: "uint256", name: "approvedAt", type: "uint256" },
          { internalType: "uint256", name: "distributedAt", type: "uint256" },
          { internalType: "uint256", name: "completedAt", type: "uint256" },
        ],
        internalType: "struct Zakat.ZakatDistribution",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum Zakat.DistributionStatus",
        name: "_status",
        type: "uint8",
      },
    ],
    name: "getDistributionsByStatus",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_donationId", type: "uint256" }],
    name: "getDonationInfo",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "address", name: "donor", type: "address" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "uint256", name: "platformFee", type: "uint256" },
          { internalType: "uint256", name: "netAmount", type: "uint256" },
          {
            internalType: "uint256",
            name: "nftCertificateId",
            type: "uint256",
          },
          { internalType: "uint256", name: "timestamp", type: "uint256" },
          { internalType: "bool", name: "isDistributed", type: "bool" },
          {
            internalType: "enum Zakat.ZakatType",
            name: "zakatType",
            type: "uint8",
          },
          { internalType: "string", name: "donorMessage", type: "string" },
        ],
        internalType: "struct Zakat.ZakatDonation",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_donor", type: "address" }],
    name: "getDonorDonations",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_organizationAddress",
        type: "address",
      },
    ],
    name: "getOrganizationDistributions",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_organizationAddress",
        type: "address",
      },
    ],
    name: "getOrganizationInfo",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "address", name: "walletAddress", type: "address" },
          { internalType: "string", name: "name", type: "string" },
          { internalType: "string", name: "contactInfo", type: "string" },
          { internalType: "string", name: "location", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          {
            internalType: "string",
            name: "registrationNumber",
            type: "string",
          },
          { internalType: "bool", name: "isVerified", type: "bool" },
          {
            internalType: "uint256",
            name: "totalDistributed",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalBeneficiaries",
            type: "uint256",
          },
          { internalType: "uint256", name: "registeredAt", type: "uint256" },
        ],
        internalType: "struct Zakat.ZakatOrganization",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalCounts",
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "i_treasury",
    outputs: [
      { internalType: "contract IQrbnTreasury", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "i_usdc",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "i_zakatNFT",
    outputs: [
      { internalType: "contract IZakatNFT", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_organizationAddress",
        type: "address",
      },
    ],
    name: "isOrganizationRegistered",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_organizationAddress",
        type: "address",
      },
      { internalType: "uint256", name: "_requestedAmount", type: "uint256" },
      { internalType: "uint256", name: "_beneficiaryCount", type: "uint256" },
      {
        internalType: "enum Zakat.DistributionType",
        name: "_distributionType",
        type: "uint8",
      },
      { internalType: "string", name: "_title", type: "string" },
      { internalType: "string", name: "_description", type: "string" },
      { internalType: "string", name: "_location", type: "string" },
    ],
    name: "proposeDistribution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_organizationAddress",
        type: "address",
      },
      { internalType: "string", name: "_name", type: "string" },
      { internalType: "string", name: "_contactInfo", type: "string" },
      { internalType: "string", name: "_location", type: "string" },
      { internalType: "string", name: "_description", type: "string" },
      { internalType: "string", name: "_registrationNumber", type: "string" },
    ],
    name: "registerZakatOrganization",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "callerConfirmation", type: "address" },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "s_availableZakatBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "s_distributionDonationIds",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "s_donationToDistribution",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "s_donorDonationIds",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "s_organizationDistributionIds",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_platformFeeBps",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "s_registeredOrganizations",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_totalCollectedFees",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_totalCollectedZakat",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "s_totalDistributedZakat",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "s_zakatDistributions",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "uint256", name: "organizationId", type: "uint256" },
      { internalType: "address", name: "organizationAddress", type: "address" },
      { internalType: "uint256", name: "requestedAmount", type: "uint256" },
      { internalType: "uint256", name: "approvedAmount", type: "uint256" },
      { internalType: "uint256", name: "distributedAmount", type: "uint256" },
      { internalType: "uint256", name: "beneficiaryCount", type: "uint256" },
      {
        internalType: "enum Zakat.DistributionType",
        name: "distributionType",
        type: "uint8",
      },
      {
        internalType: "enum Zakat.DistributionStatus",
        name: "status",
        type: "uint8",
      },
      { internalType: "string", name: "title", type: "string" },
      { internalType: "string", name: "description", type: "string" },
      { internalType: "string", name: "location", type: "string" },
      { internalType: "string", name: "reportUri", type: "string" },
      { internalType: "uint256", name: "createdAt", type: "uint256" },
      { internalType: "uint256", name: "approvedAt", type: "uint256" },
      { internalType: "uint256", name: "distributedAt", type: "uint256" },
      { internalType: "uint256", name: "completedAt", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "s_zakatDonations",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "address", name: "donor", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "platformFee", type: "uint256" },
      { internalType: "uint256", name: "netAmount", type: "uint256" },
      { internalType: "uint256", name: "nftCertificateId", type: "uint256" },
      { internalType: "uint256", name: "timestamp", type: "uint256" },
      { internalType: "bool", name: "isDistributed", type: "bool" },
      {
        internalType: "enum Zakat.ZakatType",
        name: "zakatType",
        type: "uint8",
      },
      { internalType: "string", name: "donorMessage", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "s_zakatOrganizations",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "address", name: "walletAddress", type: "address" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "contactInfo", type: "string" },
      { internalType: "string", name: "location", type: "string" },
      { internalType: "string", name: "description", type: "string" },
      { internalType: "string", name: "registrationNumber", type: "string" },
      { internalType: "bool", name: "isVerified", type: "bool" },
      { internalType: "uint256", name: "totalDistributed", type: "uint256" },
      { internalType: "uint256", name: "totalBeneficiaries", type: "uint256" },
      { internalType: "uint256", name: "registeredAt", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_newTipBps", type: "uint256" }],
    name: "setSuggestedTipPercentage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_organizationAddress",
        type: "address",
      },
    ],
    name: "unverifyZakatOrganization",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_organizationAddress",
        type: "address",
      },
    ],
    name: "verifyZakatOrganization",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
